### ISSUE TITLE
Rebuild package if "built with different version" error

### ISSUE THREAD

**Issue by ccoverstreet** [ccoverstreet/Jablko#48]
Jablko should attempt to rebuild a package if this error occurs. If it fails a second time, the module should be disabled for runtime with an error message stating which module has a build issue. 

```
[2020-12-30 12:23:44]: Error loading jablkomod "./test_modules/interfacestatus/jablkomod.so"
[2020-12-30 12:23:44]: plugin.Open("./test_modules/interfacestatus/jablkomod"): plugin was built with a different version of package github.com/ccoverstreet/Jablko/types
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x8d45de]

goroutine 1 [running]:
plugin.lookup(...)
        /usr/lib/go/src/plugin/plugin_dlopen.go:138
plugin.(*Plugin).Lookup(...)
        /usr/lib/go/src/plugin/plugin.go:40
github.com/ccoverstreet/Jablko/src/jablkomods.Initialize.func1(0xc000162152, 0x5, 0x375, 0xc000162159, 0x50, 0x36e, 0x3, 0x15a, 0x36e, 0x3)
        /home/coverstreet/Coding/Jablko_Home/Testing/Jablko/src/jablkomods/jablkomods.go:110 +0x49e
github.com/buger/jsonparser.ObjectEach(0xc00016204f, 0x215, 0x478, 0xc00015bcd8, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/coverstreet/go/pkg/mod/github.com/buger/jsonparser@v1.0.0/parser.go:1082 +0x41a
github.com/ccoverstreet/Jablko/src/jablkomods.Initialize(0xc00016204f, 0x215, 0x478, 0xc000162276, 0x4e, 0x251, 0xb191c0, 0xc00010ad20, 0x251, 0x4, ...)
        /home/coverstreet/Coding/Jablko_Home/Testing/Jablko/src/jablkomods/jablkomods.go:42 +0x23f
github.com/ccoverstreet/Jablko/src/mainapp.CreateMainApp(0xa98e3a, 0x13, 0xaaa3c8, 0x40, 0x0)
        /home/coverstreet/Coding/Jablko_Home/Testing/Jablko/src/mainapp/mainapp.go:80 +0x42d
main.main()
        /home/coverstreet/Coding/Jablko_Home/Testing/Jablko/jablko.go:45 +0x8f
exit status 2
```

**Comment by ccoverstreet** [comment]
The rebuilt plugin can only be loaded after a restart due to go plugins design. The solution to this is to allow module initialization to finish, but set a flag in jablkomods to trigger a restart. This way, all plugins are rebuilt correctly and Jablko should be able to restart with no issues.
